---
title: "Assignment 1"
output:
  html_document:
    df_print: paged
---


```{r}
link='https://github.com/mackek2/BigData/blob/main/Electric_Vehicle_Population_Data.csv?raw=true'
big=read.csv(link)
```

```{r column_Names, eval=TRUE}
names(big)
```

```{r dataSTR, eval=TRUE}
# this 'width = 70,strict.width='cut' means
# you do not want to see more than 70 characters per row.

str(big,width = 70,strict.width='cut')

```
```{r}
elecTab=table(big$County)
elecTabP=round(100*prop.table(elecTab),2)
```


```{r}
elecDF=as.data.frame(elecTabP)
names(elecDF)=c("county",'share')
elecDF$count=as.vector(elecTab)

```
```{r}
elecDF_1=elecDF[elecDF$share>=1,]
```



```{r}
library(ggplot2)
base=ggplot(data=elecDF_1,
            aes(x=county,
                y=share))
base+geom_bar(stat='identity')
```


```{r bar_gg, eval=TRUE}
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') 
plot1
```

```{r title_gg1, eval=TRUE}
titleText='How Does Electric Vehicle Use Vary by County?'
sourceText='Source: Washington State Department of Licensing \nNote: This shows a subset of counties in Washington State\n of the counties with the most electric vehicles.'

plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText) 
plot2

```

```{r units_gg1, eval=TRUE}
library(scales) # for "unit_format""

# customize Y axis
plot3 = plot2 + scale_y_continuous(breaks=c(0,20, 40,60),
                                   limits = c(0, 60), 
                                   labels=unit_format(suffix = '%'))
plot3
```

```{r title2_gg1, eval=TRUE}
#positions: 0 left / 1 right / 0.5 center
plot4 = plot3 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot4
```

```{r, eval=TRUE}
paste0(round(elecDF_1$share,2), '%')

```

```{r annot_gg1, eval=TRUE}
# creating labels:
LABELS=paste0(round(elecDF_1$share,2), '%')
###
plot5 = plot4 + geom_text(vjust=0, #hjust if flipping
                          size = 3,
                          aes(y = share ,
                              label = LABELS))
plot5# + coord_flip() # wanna flip the plot?

```

```{r orderFor_gg1, eval=TRUE}
elecDF_1=elecDF_1[order(elecDF_1$share),]
# then:
elecDF_1
```

```{r}
(countyOrd=elecDF_1[order(elecDF_1$share),'county'])
```
```{r}
plot5
```

```{r}
LABELS=paste0(round(elecDF_1$share,2), '%')
base=ggplot(data=elecDF_1,
            aes(x=county,
                y=share))
base=base + scale_x_discrete(limits=countyOrd)
base=base + theme_classic()
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity')
plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText) 
plot3 = plot2 + scale_y_continuous(breaks=c(0,20, 40,60),
                                   limits = c(0, 60), 
                                   labels=unit_format(suffix = '%'))
plot4 = plot3 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot5 = plot4 + geom_text(vjust=0, #hjust if flipping
                          size = 3,
                          aes(y = share ,
                              label = LABELS))
plot5
```

